name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18']
        os: [ubuntu-latest]
    name: Node.js ${{ matrix.node }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm install
      - run: npm run test